AdAway/build.gradle, AdAway/src/main/AndroidManifest.xml, AdAway/src/main/java/org/adaway/service/DailyListener.java, build.gradle, gradle/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties, libraries/Donations/build.gradle, libraries/Donations/src/main/AndroidManifest.xml, libraries/HtmlTextView/build.gradle, libraries/HtmlTextView/src/main/AndroidManifest.xml, libraries/RootCommands/build.gradle, libraries/RootCommands/src/main/AndroidManifest.xml, libraries/actionbarsherlock/AndroidManifest.xml, libraries/actionbarsherlock/build.gradle, libraries/actionbarsherlock/res/drawable/abs__search_dropdown_dark.xml, libraries/actionbarsherlock/res/drawable/abs__search_dropdown_light.xml
Update build env and attempt at addressing https://github.com/sufficientlysecure/ad-away/issues/635
I've tested the update seems to be working.  Can check log for time you get.  I purposely didn't include 9 in the range so everyone on older versions update at 9 while newer will be in range of 3-8.
=> Build env updates, daily update adjustments

AdAway/src/main/java/org/adaway/provider/AdAwayDatabase.java, AdAway/src/main/res/raw/help_changelog.html, CHANGELOG
update hosts-file.net and prep for a 3.0.1 release
=> Host source

AdAway/src/main/java/org/adaway/provider/AdAwayDatabase.java
=> Fix DB crash on upgrade

AdAway/src/main/java/org/adaway/provider/AdAwayDatabase.java
All tests are good now.  Can TAG at will.
=> Fix hosts source typo

AdAway/src/main/res/values-nl/strings.xml, DESCRIPTION, README.md
Update URL's in both Description & ReadMe documents
=> adaway: update urls & nl translation

AdAway/src/main/java/org/adaway/provider/AdAwayDatabase.java
=> pgl.yoyo.org now supports https

AdAway/src/main/res/values-fr/strings.xml
Just some minor typos and grammar issues fixed here.
=> Fix typos and grammar issues

AdAway/src/main/java/org/adaway/util/ApplyUtils.java, libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Remounter.java
I mistyped when i copy pasted this line
=> We want to remount when using system, not when we arent

AdAway/src/main/java/org/adaway/util/ApplyUtils.java, libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Remounter.java, libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Toolbox.java
So i was thinking about how hardcoding for /system is probably a terrible terrible idea, so instead i just used a different method to get the list of mount points, and added a toybox version of the command to the previous list of commands. This way, this should work with ToolBox, BusyBox and ToyBox, and with any file that needs permissions to mount including system.
=> A better fix for nougat

AdAway/build.gradle, AdAway/src/main/AndroidManifest.xml, AdAway/src/main/res/xml/shortcuts.xml
I used icons already available in app, but they are white...
=> Launcher shortcuts for Android 7.1 (Settings, Log DNS Requests, Your Lists)

README.md
Ive noticed a lot of people with issues that are resolved in preview builds, that have no idea how to get them. This is why there are currently two issues related to Nougat, as people are not using the fixed builds.
=> Add notes about downloading the latest preview

AdAway/src/main/java/org/adaway/util/SystemlessUtils.java
I add lot of checks to help investigate when some users get issue with systemless mode installation.
=> Improve error detecting when enabling systemless

libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/util/Utils.java
=> added /su/bin/ to su binary paths

AdAway/src/main/java/org/adaway/ui/PrefsActivity.java, AdAway/src/main/java/org/adaway/util/SystemlessUtils.java, AdAway/src/main/java/org/adaway/util/systemless/AbstractSystemlessMode.java, AdAway/src/main/java/org/adaway/util/systemless/NotSupportedSystemlessMode.java, AdAway/src/main/java/org/adaway/util/systemless/SuperSuSystemlessMode.java, AdAway/src/main/java/org/adaway/util/systemless/SuperUserSystemlessMode.java, AdAway/src/main/res/values/strings.xml
Extend systemless support to multiple root implementations
Keep ChainFire's SuperSU systemless support
Add phh's superuser systemless support
=> Add generic systemless support

.gitignore, AdAway/build.gradle, gradle.properties
You would most probably know about these i imagine.
But here is a pull request with a couple of things to think about at the very least.
Note - build working fine
=> Build updates and fixes

app/src/main/java/org/adaway/helper/PreferenceHelper.java, app/src/main/java/org/adaway/model/hostsinstall/HostsInstallModel.java, app/src/main/res/values/preferences.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
I added an option to redirect to custom IPv6 address if IPv6 is enabled in the settings above.
Nothing is translated yet.
Fixes #1115
=> Added option to change default IPv6 redirection.

app/src/main/res/values-pl/strings.xml
translation completed for the source file '/app/src/main/res/values/strings.xml'
on the 'pl' language
=> Apply translations in pl

metadata/android/eu/short_description.txt
translation completed for the source file '/metadata/android/en/short_description.txt'
on the 'eu' language
=> Apply translations in eu

metadata/android/az/full_description.txt
translation completed for the source file '/metadata/android/en/full_description.txt'
on the 'az' language
=> Apply translations in az

app/src/main/res/values-cs/strings.xml
translation completed for the source file '/app/src/main/res/values/strings.xml'
on the 'cs' language.
=> Apply translations in cs

.github/ISSUE_TEMPLATE/bug_report.md
swap out iPhone 6 and iOS for an android phone and and android version as the app is for android devices. Choice of pixel/version is arbitrary
=> Replace apple examples with android ones

.github/ISSUE_TEMPLATE/app_compatibility.md
Previously this was rendered as part of line 20 which I'm assuming is not he desired behaviour
=> Add extra line return before line 22

README.md
There was a small typo in your readme file which was preventing the images from showing up. Now that is fixed.
=> Fixed the broken image links in your readme file

app/src/main/res/values-en-rUS/strings_errors.xml
Nothing major just a typo I fixed that I came across while using the app.
=> fix typo in app/src/main/res/values-en-rUS strings_errors.xml

README.md
Hey, I was going through the Readme file and found a grammatical mistake. Have made the minor change :)
=> Fix Grammar in Readme

.github/workflows/android-ci.yml
this should fix the last set-output warning
=> Update mikepenz/gradle-dependency-submission to 0.8.5

CONTRIBUTING.md
The PR is quite self-descriptive.
=> Fix typos and some agrammatical sentences on the Contributing guidelines
